# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#My eleven themes or categories

art_theme = Category.create(name: "art", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_suprematism_2209256.png")
theatre_theme = Category.create(name: "theatre", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_theatre_1628803.png")
literature_theme = Category.create(name: "literature", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_literature_2042388.png")
music_theme = Category.create(name: "music", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_accordion_330237.png")
space_theme = Category.create(name: "space", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_spaceman_2212791.png")
ballet_theme = Category.create(name: "ballet", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_ballerina_330245+(1).png")
winter_theme = Category.create(name: "winter", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_Snowflake_1986791.png")
food_and_drink_theme = Category.create(name: "food and drink", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_Samovar_330246.png")
toys_theme = Category.create(name: "toys", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_matrioshka_330268.png")
sports_theme = Category.create(name: "sports", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_Ice_Skate_1410015.png")
forest_theme = Category.create(name: "forest", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/categoryicons/noun_birch_330314.png")

#Products

#art - 1

aivazovsky_laptop_sleeve = Product.create(name: "Laptop sleeve with Aivazovsky's 'Along the Coast' design", price: 44.99, description: "Laptop sleeve with the design of the Russian artist Ivan Aivazovsky's 1900 painting 'Along the Coast'. Larger size - fits all MacBooks.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/IvanAivazovskyalongthecoastlaptopsleeve.jpg")
goncharova_mug = Product.create(name: "Mug of Goncharova's Khorovod", price: 14.99, description: "Mug with the design of Russian avant-garde artist Natalia Goncharova 1910 painting 'Khorovod', illustrating a traditional Russian circle dance.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/Khorovodgoncharovamug.jpg")
korovin_mug = Product.create(name: "Mug of Korovin's Place d'el Opera Paris", price: 19.99, description: "A mug with the design of Russian impressionist painter Konstantin Korovin's painting, 'Place d'el Opera Paris'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/KonstantinKorovinPlacedelOperaParisMug.jpg")
composition_iv_laptop_sleeve = Product.create(name: "Laptop sleeve with Kandinsky's 'Composition IV' design", price: 44.99, description: "Laptop sleeve with the design of the Wassily Kandinsky's 1911 painting 'Composition IV'. Larger size - fits all MacBooks.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/compositionivkandinskylaptopsleeve.jpg")
composition_viii_mug = Product.create(name: "Mug of Kandinsky's 'Composition VIII'", price: 19.99, description: "A coffee-style mug with the design of Kazimir Malevich's 1923 painting, 'Composition VIII'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/compositionviiikandinskymug.jpg")
goncharova_earrings = Product.create(name: "Earrings with Goncharova design", price: 29.99, description: "Earrings with the image of a design by Russian avant garde artist Natalia Goncharova for Diagilhev's Ballet Russes.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/goncharovaearings.jpg")
kandinsky_tote = Product.create(name: "Tote bag with design of Kandinsky's 'Colour Study Square'", price: 14.99, description: "Large tote bag (48.5 x 41cm) with the design of Wassily Kandinsky's 1913 painting 'Colour Study: Squares with Concentric Circles'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/kandinskycolourstudysquaretotebag.jpg")
romantic_landscape_laptop_sleeve = Product.create(name: "Laptop sleeve with Kandinsky's 'Romantic Landscape' design", price: 44.99, description: "Laptop sleeve with the design of Wassily Kandinsky's 1911 painting 'Romantic Landscape'. Larger size - fits all MacBooks.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/kandinskyromanticlandscapelaptopsleeve.jpg")
several_circles_laptop_sleeve = Product.create(name: "Laptop sleeve with Kandinsky's 'Several Circles' design", price: 44.99, description: "Laptop sleeve with the design of Wassily Kandinsky's 1926 painting 'Several Circles'. Larger size - fits all MacBooks.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/kandinskyseveralcircleslaptopsleeve.jpg")
yellow_red_blue_laptop_sleeve = Product.create(name: "Laptop sleeve with Kandinsky's 'Yellow Red Blue' design", price: 44.99, description: "Laptop sleeve with the design of the Wassily Kandinsky's 1925 'Yellow, Red Blue'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/kandinskyyellowredbluelaptopsleeve.jpg")
korovin_phone_case = Product.create(name: "Korovin iPhone case", price: 24.99, description: "iPhone case with the design of the Russian impressionist painter Konstantin Korovin's painting, 'Place d'el Opera Paris'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/koroviniphonecase.jpg")
korovin_travel_mug = Product.create(name: "Korovin travel mug", price: 29.99, description: "Tall travel mug with the design of the Russian impressionist painter Konstantin Korovin's painting, 'Place d'el Opera Paris'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/korovintravelmug.jpg")
malevich_phone_cover = Product.create(name: "iPhone cover with Malevich's 'Dynamic Suprematism' design", price: 24.99, description: "iPhone case with the design of Kazimir Malevich's 1915 painting 'Dynamic Suprematism'", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/malevichdynamicsuprematismiPhonecover.jpg")
malevich_print = Product.create(name: "Malevich print", price: 49.99, description: "Art print (16in x 20in) of Kazimir Malevich's 1932 painting 'Woman with Rake'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/malevichprint.jpg")
malevich_mug = Product.create(name: "Mug of Malevich's 'Suprematist Composition'", price: 19.99, description: "A coffee-style mug with the design of Kazimir Malevich's 1916 painting 'Suprematist Composition'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/malevichsuprematistcompositionmug.jpg")
suprematist_print = Product.create(name: "Malevich suprematist print", price: 59.99, description: "A framed (12in x 16in) wall print of Kazimir Malevich's 1916 painting 'Suprematist Composition'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/malevichsuprematistprint.jpg")
sportsmen_placemat = Product.create(name: "Placemat with Malevich's 'Sportsmen' design", price: 29.99, description: "A pair of A3 tablemats wiith the design of Kazimir Malevich's 1931 painting 'The Sportsmen'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/malevichthesportsmenplacemat.jpg")
malevich_travel_mug = Product.create(name: "Malevich travel mug", price: 29.99, description: "Tall travel mug with the design of Kazimir Malevich's 1916 painting, 'Dynamic Suprematism'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/malevichtravelmug.jpg")
malevich_tshirt = Product.create(name: "Portrait Malevich T-Shirt", price: 29.99, description: "T-shirt with the design of Kazimir Malevich's painting 'Portrait'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/portraitmalevichtshirt.jpg")
several_circles_mug = Product.create(name: "Mug of Kandinsky's 'Several Circles'", price: 19.99, description: "A coffee-style mug with the design of Wassily Kandinsky's 1926 painting 'Several Circles'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/severalcircleskandinskymug.jpg")
sky_blue_mug = Product.create(name: "Mug of Kandinsky's 'Sky Blue'", price: 19.99, description: "A coffee-style mug with the design of Wassily Kandinsky's 1940 painting 'Sky Blue'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/skybluekandinskymug.jpg")
kandinsky_print = Product.create(name: "Print of Kandinsky's 'Succession'", price: 49.99, description: "A wall print (16in x 20in) of the Russian artist Wassily Kandinsky's 1935 painting 'Succession'", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/successionkandinskyprint.jpg")
suprematism_1916_mug = Product.create(name: "Mug of Malevich's 'Suprematism 1916'", price: 19.99, description: "A coffee-style mug with the design of Kazimir Malevich's painting 'Suprematism 1916'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/suprematism1916malevichmug.jpg")
kandinsky_travel_mug = Product.create(name: "Travel mug Kandinsky", price: 29.99, description: "Tall travel mug with the design of Wassily Kandinsky's 1923 painting 'On White II'. ", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/travelmugkandinsky.jpg")
yellow_red_blue_travel_mug = Product.create(name: "Travel mug of Kandinsky's 'Yellow Red Blue'", price: 29.99, description: "Tall travel mug with the design of Wassily Kandinsky's 1925 painting 'Yellow, Red, Blue'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/travelmugyellowredbluekandinsky.jpg")
kandinsky_phone_case = Product.create(name: "iPhone case of Kandinsky's 'Yellow Red Blue'", price: 24.99, description: "iPhone case with the design of the Russian artist Wassily Kandinsky's 1925 painting 'Yellow, Red, Blue'", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/art/yellowredbluekandinskyiphonecase.jpg")

#theatre - 2

cherry_orchard_bag = Product.create(name: "Chekhov's The Cherry Orchard Clutch bag", price: 69.99, description: "Vegan leather clutch bag with the design of Anton Chekhov's play The Cherry Orchard. Comes with a strap.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/theatre/bookclutchthecherryorhard.jpg")
chekhov_quote_print = Product.create(name: "Chekhov quote wall print", price: 34.99, description: "A framed 'floating quote wall print of the Russian playright Anton Chekhov's quote 'Don't tell me the moon is shining; show me the glint of light on broken glass.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/theatre/chekhovfloatingquote.jpg")
chekhov_quote_love = Product.create(name: "Framed print of a Chekhov quote about love", price: 9.99, description: "A framed wall print of the Russian playright Anton Chekhov's quote 'The soft April night is looking at my windows and caressingly winking at me with its stars. I can't sleep. I am so happy.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/theatre/chekhovquote.jpg")
cross_stitch_bolshoi = Product.create(name: "Cross stitch kit of the Bolshoi theatre in Moscow", price: 39.99, description: "A kit to make a cross stitch of the famous Bolshoi theatre in Moscow. Finished size is 50cm x 30cm, includes a needle, threads, booklet with instructions in English, Russian, German, French, Italian and Spanish.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/theatre/crossstitchbolshoi.jpg")
playright_postcards = Product.create(name: "Set of postcards of celebrated Russian playrights", price: 14.99, description: "A set of 16 postcards of portraits of celebrated Russian playrights", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/theatre/russianplayrights.jpg")

#literature - 3

dostoyevsky_print = Product.create(name: "Dostoyevsky print", price: 34.99, description: "A2 print with potrait of the Russian novelist Fyodor Dostoyevsky, in his own words (from the opening of Crime and Punishment.)", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/Dostoyevskyportraitprint.jpg")
anna_karenina_bag = Product.create(name: "Anna Karenina book bag", price: 89.99, description: "A book shaped purse with the design of the Leo Tolstoy novel, 'Anna Karenina'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/annakareninabookbag.jpg")
anna_karenina_pillowcase = Product.create(name: "Anna Karenina pillow case (Russian)", price: 49.99, description: "Pillow cover with the design of the Leo Tolstoy novel, 'Anna Karenina' - Russian version", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/annakareninarussianpillowcover.jpg")
anna_karenina_shawl_english = Product.create(name: "Anna Karenina shawl (English)", price: 49.99, description: "Scarf or shawl with a design of the Leo Tolstoy novel 'Anna Karenina' - English version.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/annakareninashawlenglish.jpg")
anna_karenina_shawl_russian = Product.create(name: "Anna Karenina shawl (Russian)", price: 49.99, description: "Scarf or shawl with a design of the Leo Tolstoy novel 'Anna Karenina' - Russia version.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/annakareninashawlrussian.jpg")
bulgakov_bag_english = Product.create(name: "The Master and Margarita book bag (English)", price: 69.99, description: "A leather purse in the shape and design of the Mikhail Bulgakov book 'The Master and Margarita'. English language cover.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/leatherbookpursemasterandthemargaritaenglish.jpg")
bulgakov_bag_russian = Product.create(name: "The Master and Margarita book bag (Russian)", price: 69.99, description: "A vegan leather purse in the shape and design of the Mikhail Bulgakov book 'The Master and Margarita'. Russian language cover.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/masterandmagaritarussian.jpg")
dostoyevsky_pillowcase = Product.create(name: "Crime and Punishment pillow case (English)", price: 49.99, description: "Pillow cover with the design of the Fyodor Dostoyevsky novel 'Crime and Punishment'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/crimeandpunishmentpillowcoverenglish.jpg")
dostoyevsky_shawl = Product.create(name: "Crime and Punishment shawl (English)", price: 49.99, description: "Scarf or shawl with a design of the Fyodor Dostoyevsky novel, 'Crime and Punishment' - English version.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/crimeandpunishmentshawlenglish.jpg")
dr_zhivago_quote = Product.create(name: "Dr. Zhivago Quote poster", price: 24.99, description: "13in x 19in poster of a quote from the Boris Pasternak novel Doctor Zhivago about love.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/drzhivagofloatingquote.jpg")
pushkin_book_bag_image = Product.create(name: "Pushkin book bag with image", price: 79.99 , description: "A book shaped purse with the image and and name (in Russian) of the Russian poet Alexander Pushkin.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/pushkinbookbag.jpg")
pushkin_book_bag = Product.create(name: "Pushkin book bag", price: 79.99, description: "A book shaped purse with the design of the complete collection of Alexander Pushkin's poems (Russian language cover).", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/pushkinbookbag2.jpg")
tolstoy_quote_print = Product.create(name: "Tolstoy quote print", price: 44.99, description: "A wall print of a quote by the Russian author Leo Tolstoy - Wrong does not cease to be wrong because the majority share in it.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/tolstoyquote.jpg")
mini_war_and_peace = Product.create(name: "Mini War and Peace", price: 7.99, description: "A very miniature version of the Leo Tolstoy epic 'War and Peace' designed to read in one sitting!", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/war-and-peace-miniature-edition.jpg")
war_and_peace_pillowcase = Product.create(name: "War and Peace pillow case (English)", price: 49.99, description: "Pillow cover with the design of the Leo Tolstoy novel, 'War and Peace' - English version.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/warandpeacepillowcasenglish.jpg")
war_and_peace_shawl = Product.create(name: "War and Peace shawl (English)", price: 49.99, description: "Scarf or shawl with a design of the Leo Tolstoy novel, 'War and Peace' - English version.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Literature/warandpeaceshawlenglish.jpg")

#music - 4

tchaikovsky_pic = Product.create(name: "Tchaikovsky guitar pic", price: 49.99, description: "Custom designed silver guitar pic with the image of Russian composer Pyotr Ilyich Tchaikovsky.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/tchaikovskyguitarpic.jpg")
tchaikovsky_journal = Product.create(name: "Tchaikovsky journal", price: 19.99, description: "Hardcover journal (13.2cm x 18.6cm) with a design of the Russian composer Pyotr Ilyich Tchaikovsky.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/tchaikovskyjournal.jpg")
scriabin_journal = Product.create(name: "Scriabin journal", price: 19.99, description: "Hardcover journal (13.2cm x 18.6cm) with a design of the Russian composer Alexander Scriabin.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/Scriabinjournal.jpg")
scriabin_tote = Product.create(name: "Scriabin tote bag", price: 24.99, description: "Large (46cm x 46cm) tote bag with design of the Russian composer Alexander Scriabin", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/Scriabintotebag.jpg")
accordion = Product.create(name: "Children's accordion", price: 79.99, description: "Vintage-style children's Russian accordion. 25cm x 21cm.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/childrensaccordian.jpg")
nutcracker_score = Product.create(name: "Nutcracker score print", price: 9.99, description: "Print poster of the score of the Nutcracker Suite by the Russian composer Pyotr Ilyich Tchaikovsky", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/nutcrackerprintscore.jpg")
prokofiev_journal = Product.create(name: "Prokofiev journal", price: 19.99, description: "Hardcover journal (13.2cm x 18.6cm) with a design of the Russian composer Sergei Prokofiev.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/prokofievjournal.jpg")
prokofiev_tote = Product.create(name: "Prokofiev tote bag", price: 24.99, description: "Large (46cm x 46cm) tote bag with design of the Russian composer Sergei Prokofiev", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/prokofievtotebag.jpg")
rachmaninoff_tote = Product.create(name: "Rachmaninoff tote bag", price: 24.99, description: "Large (46cm x 46cm) tote bag with design of the Russian composer Sergei Rachmaninoff.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/rachmaninofftotebag.jpg")
rachmaninoff_journal = Product.create(name: "Rachmaninoff journal", price: 19.99, description: "Hardcover journal (13.2cm x 18.6cm) with a design of the Russian composer Sergei Rachmaninoff.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/rachmaninoffjournal.jpg")
shostakovich_pic = Product.create(name: "Shostakovich guitar pic", price: 49.99, description: "Custom designed silver guitar pic with the image of Russian pianist Dmitri Shostakovich", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/shostakovichguitarpic.jpg")
shostakovich_journal = Product.create(name: "Shostakovich journal", price: 19.99, description: "Hardcover journal (13.2cm x 18.6cm) with a design of the Russian composer Dmitri Shostakovich.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/music/shoshtakovichjournal.jpg")

#space - 5

soviet_space_prints = Product.create(name: "Four Space-themed wall prints", price: 99.99, description: "A set of 4 A2 space-themed wall prints", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/SovietSpacePrints.jpg")
be_first_phone_case = Product.create(name: "iPhone case - 'Be First Like Gagarin'", price: 29.99, description: "An iPhone case with the image of the first man in space - Yuri Gagarin, and the slogan, 'Be First Like Gagarin'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/befirstlikegagariniphonecase.jpg")
cosmonauts_tote = Product.create(name: "Tote bag with Cosmonauts", price: 19.99, description: "A 33cm x 33cm tote bag with a Cosmonaut design", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/cosmonautstotebag.jpg")
gagarin_notebook = Product.create(name: "Gagarin spiral notebook", price: 14.99, description: "A rule-lined spiral notebook with the image of the first man in space, Yuri Gagarin. 15 1/4 cm x 20 1/4 cm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/gagarinnotebook.jpg")
gagarin_tote = Product.create(name: "Gagarin tote bag", price: 24.99, description: "Large tote bag (46cm x 46cm) with the design of the first man in space - Yuri Gagarin", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/gagarintotebag.jpg")
gagarin_tshirt = Product.create(name: "Gagarin T-Shirt", price: 29.99, description: "T-Shirt with the design of the first man in space, Yuri Gagarin.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/gagarintshirt.jpg")
ipad_case_cosmonaut = Product.create(name: "Cosmonaut iPad case", price: 49.99, description: "Hard iPad case with a cosmonaut design", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/ipadcasecosmonaut.png")
cosmonaut_matryoshka = Product.create(name: "Cosmonaut matryoshka", price: 44.99, description: "Traditional handmade Russian nesting doll or 'matryoshka' with the design of a cosmonaut and three space dogs (Laika, Belka and Strelka).", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/matroshkacosmonaut.jpg")
cosmonaut_notebook = Product.create(name: "Cosmonaut notebook", price: 14.99, description: "A rule-lined spiral notebook with an artistic Cosmonaut design", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/notebookcosmonaut.jpg")
poyekhali_notebook = Product.create(name: "Поехали notebook", price: 14.99, description: "A rule-lined spiral notebook with a design depicting a cosmonaut, rocket and the slogan Поехали!", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/poyekhalinotebook.jpg")
poyekhali_travel_mug = Product.create(name: "Поехали travel mug", price: 29.99, description: "Tall travel mug with a design depicting a cosmonaut, rocket and the slogan Поехали!", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/poyekhalitravelmug.jpg")
prints_cosmonauts = Product.create(name: "Cosmonauts print", price: 24.99, description: "Hand-drawn wall print of a Soviet cosmonaut. 297 mm x 210mm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/printscosmonauts.jpg")
cosmos_fridge_magnets = Product.create(name: "Cosmos fridge magnets", price: 9.99, description: "Set of 6 retro fridge magnets (7cm x 10cm each) depicting the Soviet space race", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/retrocosmosfridgemagnets.jpg")
soviet_cosmonaut_matryoshka = Product.create(name: "Soviet cosmonaut matryoshka", price: 49.99, description: "Handmade, traditional Russian nesting doll, or 'matryoshka', but with the design of a team of Soviet cosmonauts", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/sovietcosmonautmatroshka.jpg")
soviet_rocket_print = Product.create(name: "Soviet rocket print", price: 44.99, description: "An A2 wall print depicting a rocket in flight", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/sovietrocketprint.jpg")
soviet_space_station_print = Product.create(name: "Soviet space station print", price: 44.99, description: "An A2 wall print depicting the Soviet space station", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/sovietspacestationprint.jpg")
spacewalk_print = Product.create(name: "Spacewalk print", price: 44.99, description: "An A2 wall print depicting a spacewalk", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/spacewalkcosmonautsprint.jpg")
spacewalk_pendant = Product.create(name: "Spacewalk pendant", price: 29.99, description: "Handmade pendant with the design of a spacewalk. Comes with an 18inch gold chain", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/spacewalkpendant.jpg")
sputnik_pendant_necklace = Product.create(name: "Sputnik pendant", price: 29.99, description: "Handmade pendant depicting the first satellite, Sputnik", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/sputnikpendantnecklace.jpg")
sputnik_print = Product.create(name: "Sputnik print", price: 44.99, description: "An A2 wall print depicting the first satellite, Sputnik", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/sputnikprint.jpg")
tereshkova_tote = Product.create(name: "Tereshkova tote bag", price: 19.99, description: "A tote bag with a design depicting the first woman in space, Valentina Tereshkova", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/tereshkovatotebag.jpg")
tshirt_vostok = Product.create(name: "Vostok t-shirt", price: 24.99, description: "Cotton T-shirt with a retro design depicting Vostok 3 and 4.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/tshirtvostok3and4.jpg")
women_cosmonauts_tote = Product.create(name: "Tote bag with Women cosmonauts design. 33cm x 33cm", price: 14.99, description: "A tote bag depicting women cosmonauts", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/womencosmonauts.jpg")
women_in_science_print = Product.create(name: "Wall print celebrating Women in Science", price: 44.99, description: "A wall print (11 inch x 14inch) poster celebrating Women in Science depicts the first woman in space, Soviet cosmonaut Valentina Tereshkova", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/Space/womeninscienceprinttereshkova.jpg")

#ballet - 6

binoculars = Product.create(name: "Mariinsky Theatre glasses", price: 49.99, description: "Ballet and opera binoculars from the Mariinsky theatre, Saint Petersburg. Comes in a soft leather case with a cloth for cleaning.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/balletmarinskytheatreglasses.jpg")
diaghilev = Product.create(name: "Framed poster of Diaghilev's Ballets Russes", price: 14.99, description: "A framed poster of Dialghilev's Ballets Russes", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/diagilhevposter.jpg")
blue_nutcracker_pendant = Product.create(name: "Blue pendant necklace with nutcracker ballet dancers", price: 19.99, description: "A 1 inch square glass pendant, featuring the Nutcracker ballet, with an 18in green organza ribbon", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/nutcrackerballetpendant.jpg")
green_nutcracker_pendant = Product.create(name: "Green pendant necklace with Nutcracker design", price: 19.99, description: "A 1 inch square glass pendant featuring the Nutcracker ballet Snowflake dancers, with an 18in blue organza ribbon", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/nutcrackerpendant2.jpg")
dark_green_nutcracker_pendant = Product.create(name: "Dark dreen and white pendant necklace with Nutcracker design", price: 19.99, description: "A 1 inch square glass pendant featuring the Nutcracker ballet, with a white organza ribbon", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/nutcrackerpendant3.jpg")
nutcracker_postcard = Product.create(name: "Postcard with Nutcracker design", price: 4.99, description: "Vintage postcard of three ballet dancers performing the Nutcracker", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/nutcrackerpostcard.jpg")
nutcracker_tote_bag = Product.create(name: "Tote bag with Nutcracker design", price: 24.99, description: "100% cotton canvas bag with a design from the Nutcracker ballet. 14.75 x 14.75, with 22in handles.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/nutcrackertotebag.jpg")
white_swan_postcard = Product.create(name: "Postcard with Swan lake design - white swan", price: 4.99, description: "Vintage postcard of two ballet dancers performing Swan Lake", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/swanlakepostcard.jpg")
black_swan_postcard = Product.create(name: "Postcard with Swan lake design - black swan", price: 4.99, description: "Vintage postcard of two ballet dancers (male and female) performing Swan Lake, with audience members in the background", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/swanlakepostcard2.jpg")
indoors_swan_lake = Product.create(name: "Black and white Swan lake print - indoors", price: 24.99, description: "A print of Tchaikovsky's ballet, Swan Lake, illustrating a scene of Odile, the black swan at the ballroom dance. Approx 21cm x 30cm.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/swanlakeprint.jpg")
outdoors_swan_lake = Product.create(name: "Black and white Swan lake print - outdoors", price: 24.99, description: "A print of Tchaikovsky's ballet, Swan Lake, illustrating a scene where Odette, the white swan is dancing by the lake under the moonlight. Approx 21cm x 30cm.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/swanlakeprint2.jpg")
snow_queen_tote = Product.create(name: "Tote bag with ballet design (snow queen)", price: 24.99, description: "100% cotton canvas bag with a design of snow queen ballet design. 14.75 x 14.75, with 22in handles.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/ballet/totebagsnowqueen.jpg")

#winter - 7

december = Product.create(name: "December", price: 499.99, description: "'An original oil painting by the Siberian artist Sergey Avdeev. 40cm x 50cm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/winter/decembercityscape.jpg")
sleeping_forest = Product.create(name: "Sleeping Forest", price: 99.99, description: "An original oil painting by the Siberian artist Sergey Avdeev. 25cm x 35cm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/winter/forestinwinter.jpg")
old_house = Product.create(name: "An old house", price: 149.99, description: "An original oil painting by the Siberian artist Sergey Avdeev. 50cm x 60cm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/winter/oldhousewintercityscapepainting.jpg")
pigeons = Product.create(name: "Pigeons in the park", price: 199.99, description: "An original oil painting by the Siberian artist Mary Batmanyan. 45cm x 55cm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/winter/pidgeonsintheparkpainting.jpg")
shishkov_house = Product.create(name: "Shishkov house winter snow landscape", price: 99.99, description: "An original oil painting by the Siberian artist Sergey Avdeev. 25cm x 35cm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/winter/wintercityscapepainting.jpg")
sunday_melancholy = Product.create(name: "Sunday Melancholy", price: 199.99, description: "An original oil painting by the Siberian artist Sergey Avdeev. 50cm x 60cm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/winter/sundaymelancholypainting.jpg")
snowman_matryoshka = Product.create(name: "Snowman matryoshka doll", price: 24.99, description: "A traditional Russian nesting doll or 'matryoshka', but as a set of 5 snowmen", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/winter/snowmanmatroshka.jpg")
santa_matryoshka = Product.create(name: "Santa and snowmaiden matryoshka doll", price: 24.99, description: "A traditional Russian nesting doll or 'matryoshka', but as a set of Santa Claus, a snow maiden and a snowman.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/winter/snowmansnowmaidenmatroshka.jpg")
winter_coasters = Product.create(name: "Set of 6 winter-themed cork coasters", price: 29.99, description: "A set of 6 cork-based coasters decorated with illustrations of winter scenes by the artist Yuri Vasnetsov. 10cm x 10cm each", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/winter/wintercoasters.jpg")

#food and drink - 8

khokhloma_cups = Product.create(name: "Khokhloma cups", price: 19.99, description: "A pair of cups with a traditional Khokhloma design", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/Khohlomacups.jpg")
khokhloma_spoons = Product.create(name: "Khokhloma spoons", price: 19.99, description: "A pair of traditional Khokhloma spoons (one red, one black)", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/Khokhlomaspoons.jpg")
khokhloma_teapot = Product.create(name: "Khokhloma teapot", price: 44.99, description: "A teapot with a traditional Khokhloma design", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/Khokhlomateapot.jpg")
khokhloma_tray = Product.create(name: "Khokhloma tray", price: 24.99, description: "A large tray or plate with a traditional Khokhloma design", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/Khokhlomatray.jpg")
alenka = Product.create(name: "Alenka chocolate bar", price: 1.99, description: "A milk chocolate bar 'Alenka' by the Russian chocolate company 'Red October'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/alenkachocolatebar.jpg")
apple_chopping_board = Product.create(name: "Apple-shaped Khokhloma chopping board", price: 29.99, description: "A chopping board (20cm x 26cm) in the shape of an apple, with a traditional Khokhloma design", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/appleshapedKhokhlomachoppingboard.jpg")
babaeyevksy = Product.create(name: "Babaeyevsky chocolate bar", price: 0.99, description: "A popular Russian chocolate bar", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/babaeyevksychocolatebar.jpg")
creme_brulee_truffles = Product.create(name: "Bag of Alenka creme brulee truffles", price: 2.99, description: "A 250g bag of small chocolate truffles, with a creme brulee flavour. Part of the Red October chocolate factory's Alenka brand.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/bagofcremebruleealenkatruffles.jpg")
bears_to_the_forest = Product.create(name: "Bag of bears to the forest chocolates", price: 2.99, description: "A 200g bag of small chocolate truffles, with a caramel filling. Brand 'Bears to the Forest'.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/bearstotheforesttruffles.png")
chocolate_truffles = Product.create(name: "Dark chocolate truffles", price: 3.99, description: "A 300g bag of dark chocolate truffles", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/chocolatetruffles.jpg")
fridge_magnet_samovar = Product.create(name: "Samovar fridge magnets", price: 19.99, description: "A set of four small fridge magnets depicting a traditional samovar", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/fridgemagnetsamovar.jpg")
pear_chopping_board = Product.create(name: "Pear-shaped Khokhloma chopping board", price: 29.99, description: "A chopping board (29cm x 18cm) in the shape of a pear, with a traditional Khokhloma design", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/pearshapedKhokhlomachoppingboard.jpg")
red_october_chocs_1 = Product.create(name: "Bear-themed mini wafer chocolates", price: 3.99, description: "A 200g bag of mini wafer filled chocolates. Bear theme.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/redoctoberchocolates1.jpg")
red_october_chocs_2 = Product.create(name: "Squirrel-themed mini chocolates with nuts", price: 3.99, description: "A 200g bag of mini chocolates with a nut filling. Squirrel theme.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/redoctoberchocolates2.jpg")
red_october_nougat = Product.create(name: "Bear-themed mini nougat-filled truffles", price: 3.99, description: "A 200g bag of mini nougat filled truffles. Bear theme.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/redoctobernougattruffles.png")
samovar = Product.create(name: "Mini samovar", price: 44.99, description: "Mini samovar souvenir, metal, vintage design.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/samovar.jpg")
small_alenka_wafer_chocs = Product.create(name: "Bag of mini alenka wafer chocolates", price: 3.99, description: "A 250g bag of small chocolate bars, with a wafer filling. Part of the Red Octboer chocolate factory's Alenka brand", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/foodanddrink/smallalenkawafterchocolates.jpg")

#toys - 9

cheburashka_figurine = Product.create(name: "Crocodile Gena and Cheburashka wooden figures", price: 24.99, description: "Handmade wooden carved figurines of the Soviet cartoon characters Cheburashka and Crocodile Gena.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/CrocodileGenaandCheburashkawoodenfigurines.jpg")
balalaika_figurine = Product.create(name: "Balalaika player wooden figurine", price: 24.99, description: "Handmade wooden figurine of a balalaika player", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/balalaikaplayerfigurine.jpg")
beer_figurine = Product.create(name: "Beer drinker wooden toy", price: 24.99, description: "Handmade wooden figurine of a beer enthusiast", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/beerdrinkerwoodentoy.jpg")
dino_matryoshka = Product.create(name: "Dinosaur matryoshka", price: 24.99, description: "Traditional Russian nesting doll or 'matryoshka', but with a set of 5 dinosaurs", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/dinosaurmatroshka.jpg")
fairytale_matroshka = Product.create(name: "Fairytale matryoshka", price: 39.99, description: "Traditional Russian nesting doll or 'matryoshka'. The set are painted with a design of different fairytale characters. Larger size (18cm x 8cm).", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/fairytalesmatroshka.jpg")
girl_cat_figurine = Product.create(name: "Girl and cat wooden toy", price: 24.99, description: "Handmade wooden toy of a girl and cat on a swing", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/girlandcatwoodentoy.jpg")
masha_bear_figurine = Product.create(name: "Masha and the bear wooden figurine", price: 24.99, description: "Handmade wooden carved figurine of cartoon characters Masha and the bear", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/mashaandthebearwoodenfigurine.jpg")
rooster_matryoshka = Product.create(name: "Rooster matryoshka", price: 39.99, description: "Traditional Russian nesting doll or 'matryoshka'. Rooster design, larger doll size (14cm x 6cm).", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/matroshkarooster.jpg")
milkmaid_matryoshka = Product.create(name: "Milkmaid and cow wooden figurine", price: 24.99, description: "Handmade wooden carved figurine of a milkmaid and a cow.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/milkmaidandcowfigurine.jpg")
penguin_matryoshka = Product.create(name: "Penguin matryoshka", price: 24.99, description: "Traditional Russian nesting doll or 'matryoshka', but with a set of 5 penguins", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/penguinmatroshka.jpg")
banya_figurine = Product.create(name: "Russian banya wooden figurine", price: 24.99, description: "Handmade wooden carved figurine 'In the bath' of a Russian banya enthusiast", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/russianbanyafigurine.jpg")
musician_figurine = Product.create(name: "Russian musician wooden figurine", price: 24.99, description: "Handmade wooden carved figurine of a Russian musician", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/toys/woodenrussianmusicianfigurine.jpg")

#sports - 10

world_cup_map = Product.create(name: "2018 FIFA world cup map poster", price: 19.99, description: "A2 wall print mapping the 2018 World Cup in Russia", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/2018worldcupmap.jpg")
world_cup_poster = Product.create(name: "2018 FIFA world cup poster", price: 19.99, description: "A2 official poster print of the 2018 FIFA World Cup in Russia", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/2018worldcupposter.jpg")
figure_skater_poster = Product.create(name: "Figure skater poster", price: 44.99, description: "Limited edition print poster with a retro design of a Russian figure skater. Large size (13inch x 19 inch)", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/figureskaterposter.jpg")
ice_hockey_mug = Product.create(name: "Ice hockey mug", price: 12.99, description: "Mug with cartoon design of the Russian ice hockey team", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/icehockeyrussiamug.jpg")
ice_hockey_notebook = Product.create(name: "Ice hockey notebook", price: 12.99, description: "Ruled notedbook with cartoon design of the Russian ice hockey tea", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/icehockeyrussianotebook.jpg")
hockey_stick = Product.create(name: "Collectable vintage hockey stick", price: 29.99, description: "Vintage hockey stick of the 1985 USSR national team", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/icehockeystick.jpg")
hockey_tote = Product.create(name: "Ice hockey tote bag", price: 19.99, description: "41cm x 41cm tote bag with cartoon design of the Russian ice hockey team", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/icehockeytotebagrussia.jpg")
basketball_print = Product.create(name: "Moscow Olympics Basketball print", price: 49.99, description: "A2 wall print poster depicting a basketball game in the 1980 Moscow Olympics", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/moscowolympicsbasketballprint.jpg")
cycling_print = Product.create(name: "Moscow Olympics Cycling print", price: 49.99, description: "A2 wall print poster depicting a cyclist in the 1980 Moscow Olympics", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/moscowolympicscyclingprint.jpg")
gymnastics_print = Product.create(name: "Moscow Olympics Gymnastics print", price: 49.99, description: "A2 wall print poster depicting a gymnast in the 1980 Moscow Olympics", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/moscowolympicsprint.jpg")
swimmer_pendant = Product.create(name: "Moscow Olympics swimmer pendant", price: 29.99, description: "Pendant necklace with design of a swimmer from the 1980 Moscow Olympics. Pendant is 4.3cm x 2.15cm and comes with 18inch gold chain.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/moscowolympicsswimmerpendant.jpg")
figure_skater_mug = Product.create(name: "Figure skater mug", price: 19.99, description: "A mug with a design of the Russian flag with a silhouette of a figure skater in the foreground", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/russianfigureskatermug.jpg")
ice_hockey_poster = Product.create(name: "Retro ice hockey poster", price: 29.99, description: "Print of a Soviet ice hockey poster. 12inch x 18inch", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/sports/russianicehockeyposter.jpg")

#forest - 11

birch_tree_coaster = Product.create(name: "Glass coaster with birch tree design", price: 8.99, description: "Glass coaster with an illustration by the artist Yuri Vasnetsov, of a birch tree in the sun. 10cm x 10cm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/birchtreecoaster.jpg")
birch_trees_painting = Product.create(name: "Birch trees", price: 79.99, description: "An original oil painting by the Siberian artist Mary Batmanyan. 35cm x 45cm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/birchtreespainting.jpg")
dancing_cats_tablemat = Product.create(name: "Dancing cats table mat and coaster", price: 19.99, description: "Tablemat and coaster set with an illustration by the artist Yuri Vasnetsov, of dancing cats", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/catsplacematandcoaster.jpg")
pine_branches = Product.create(name: "On the pine branches", price: 499.99, description: "An original oil painting by the Siberian artist Sergey Avdeev. 70cm x 50cm", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/forestbirdsonthetree.jpg")
rainbow_tablemat = Product.create(name: "Forest rainbow table mat and coaster", price: 19.99, description: "Tablemat and coaster set with an illustration by the artist Yuri Vasnetsov, of a forest scene with a rainbow in the background", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/forestrainbowplacematandcoaster.jpg")
hedgehog_tablemat = Product.create(name: "Hedgehog table mat and coaster", price: 19.99, description: "Tablemat and coaster set with an illustration by the artist Yuri Vasnetsov, of a forest scene with a hedgehog wearing red boots", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/hedgehogpplacemat.jpg")
hedgehog_notebook = Product.create(name: "Hedgehog notebook", price: 9.99, description: "A5 notebook with lined sheets. Illustration is by the artist Yuri Vasnetsov, of a forest scene featuring a hedgehog wearing red boots.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/hedgehognotebook.jpg")
forest_matryoshka = Product.create(name: "Matryoshka with forest design", price: 39.99, description: "Traditional Russian nesting doll or 'matryoshka'. Forest design, larger doll size (18cm x 8cm).", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/matroshkaforest.jpg")
old_birch = Product.create(name: "The old birch", price: 49.99, description: "An original oil painting by the Siberian artist Sergey Avdeev. 15cm x 20cm.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/oldbirchforestlandscape.jpg")
owl_print = Product.create(name: "Owl, magpie and rabbit art print", price: 19.99, description: "A print of an illustration by the artist Yuri Vasnetsov of an owl, rabbit and magpie eating lunch together. 12 inch x 10 inch", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/owlartprint.jpg")
owl_chopping_board = Product.create(name: "Chopping board with owl design", price: 24.99, description: "A chopping board with a design by the artist Yuri Vasnetsov of an owl, rabbit and magpie eating lunch together. 27cm diameter, or 36.4cm with handle.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/owlchoppingboard.jpg")
owl_notebook = Product.create(name: "Owl notebook", price: 9.99, description: "A5 notebook with lined sheets. Illustration is by the artist Yuri Vasnetsov, of a forest scene featuring an owl, magpie and rabbit eating lunch together", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/owlnotebook.jpg")
owl_tablemat = Product.create(name: "Owl table mat and coaster", price: 19.99, description: "Tablemat and coaster set with an illustration by the artist Yuri Vasnetsov, of an owl, magpie and rabbit eating lunch together", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/owlplacematandcoaster.jpg")
fridge_magnet = Product.create(name: "Forest scene fridge magnet", price: 29.99, description: "Handmade, embroidery art fridge magnet of a forest scene by the Russian artist Vera Shimunia", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/printedfridgemagnet.jpg")
rabbit_tablemat = Product.create(name: "Rabbit table mat and coaster", price: 19.99, description: "Tablemat and coaster set with an illustration by the artist Yuri Vasnetsov, of rabbit wearing red boots", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/rabbitplacematandcoaster.jpg")
rainbow_chopping_board = Product.create(name: "Chopping board with rainbow design", price: 24.99, description: "A chopping board with a design by the artist Yuri Vasnetsov of a forest scene with a rainbow in the background. 27cm diameter, or 36.4cm with handle.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/rainbowchoppingboard.jpg")
rainbow_notebook = Product.create(name: "Forest rainbow notebook", price: 9.99, description: "A5 notebook with lined sheets. Illustration is by the artist Yuri Vasnetsov, of a forest scene with a rainbow in the background.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/rainbownotebook.jpg")
four_tablemats = Product.create(name: "Four forest-themed tablemats", price: 49.99, description: "Set of four tablemats each with a different design of a forest scene. Illustrations are by the artist Yuri Vasnetsov.", image_url: "https://s3.eu-west-2.amazonaws.com/zimaproducts/forest/setof4forestthemedplacemats.jpg")


# product_categories

ProductCategory.create(product: aivazovsky_laptop_sleeve, category: art_theme)
ProductCategory.create(product: goncharova_mug, category: art_theme)
ProductCategory.create(product: korovin_mug, category: art_theme)
ProductCategory.create(product: composition_iv_laptop_sleeve, category: art_theme)
ProductCategory.create(product: composition_viii_mug, category: art_theme)
ProductCategory.create(product: goncharova_earrings, category: art_theme)
ProductCategory.create(product: kandinsky_tote, category: art_theme)
ProductCategory.create(product: romantic_landscape_laptop_sleeve, category: art_theme)
ProductCategory.create(product: several_circles_laptop_sleeve, category: art_theme)
ProductCategory.create(product: yellow_red_blue_laptop_sleeve, category: art_theme)
ProductCategory.create(product: korovin_phone_case, category: art_theme)
ProductCategory.create(product: korovin_travel_mug, category: art_theme)
ProductCategory.create(product: malevich_phone_cover, category: art_theme)
ProductCategory.create(product: malevich_print, category: art_theme)
ProductCategory.create(product: malevich_mug, category: art_theme)
ProductCategory.create(product: suprematist_print, category: art_theme)
ProductCategory.create(product: sportsmen_placemat, category: art_theme)
ProductCategory.create(product: malevich_travel_mug, category: art_theme)
ProductCategory.create(product: malevich_tshirt, category: art_theme)
ProductCategory.create(product: several_circles_mug, category: art_theme)
ProductCategory.create(product: sky_blue_mug, category: art_theme)
ProductCategory.create(product: kandinsky_print, category: art_theme)
ProductCategory.create(product: suprematism_1916_mug, category: art_theme)
ProductCategory.create(product: kandinsky_travel_mug, category: art_theme)
ProductCategory.create(product: yellow_red_blue_travel_mug, category: art_theme)
ProductCategory.create(product: kandinsky_phone_case, category: art_theme)
ProductCategory.create(product: cherry_orchard_bag, category: theatre_theme)
ProductCategory.create(product: chekhov_quote_print, category: theatre_theme)
ProductCategory.create(product: chekhov_quote_print, category: literature_theme)
ProductCategory.create(product: chekhov_quote_love, category: theatre_theme)
ProductCategory.create(product: chekhov_quote_love, category: literature_theme)
ProductCategory.create(product: cross_stitch_bolshoi, category: theatre_theme)
ProductCategory.create(product: playright_postcards, category: theatre_theme)
ProductCategory.create(product: dostoyevsky_print, category: literature_theme)
ProductCategory.create(product: anna_karenina_bag, category: literature_theme)
ProductCategory.create(product: anna_karenina_pillowcase, category: literature_theme)
ProductCategory.create(product: anna_karenina_shawl_english, category: literature_theme)
ProductCategory.create(product: anna_karenina_shawl_russian, category: literature_theme)
ProductCategory.create(product: bulgakov_bag_english, category: literature_theme)
ProductCategory.create(product: bulgakov_bag_russian, category: literature_theme)
ProductCategory.create(product: dostoyevsky_pillowcase, category: literature_theme)
ProductCategory.create(product: dostoyevsky_shawl, category: literature_theme)
ProductCategory.create(product: dr_zhivago_quote, category: literature_theme)
ProductCategory.create(product: pushkin_book_bag_image, category: literature_theme)
ProductCategory.create(product: pushkin_book_bag, category: literature_theme)
ProductCategory.create(product: tolstoy_quote_print, category: literature_theme)
ProductCategory.create(product: mini_war_and_peace, category: literature_theme)
ProductCategory.create(product: war_and_peace_pillowcase, category: literature_theme)
ProductCategory.create(product: war_and_peace_shawl, category: literature_theme)
ProductCategory.create(product: tchaikovsky_pic, category: music_theme)
ProductCategory.create(product: tchaikovsky_journal, category: music_theme)
ProductCategory.create(product: scriabin_journal, category: music_theme)
ProductCategory.create(product: scriabin_tote, category: music_theme)
ProductCategory.create(product: accordion, category: music_theme)
ProductCategory.create(product: nutcracker_score, category: music_theme)
ProductCategory.create(product: nutcracker_score, category: ballet_theme)
ProductCategory.create(product: prokofiev_journal, category: music_theme)
ProductCategory.create(product: prokofiev_tote, category: music_theme)
ProductCategory.create(product: rachmaninoff_tote, category: music_theme)
ProductCategory.create(product: rachmaninoff_journal, category: music_theme)
ProductCategory.create(product: shostakovich_pic, category: music_theme)
ProductCategory.create(product: shostakovich_journal, category: music_theme)
ProductCategory.create(product: soviet_space_prints, category: space_theme)
ProductCategory.create(product: be_first_phone_case, category: space_theme)
ProductCategory.create(product: cosmonauts_tote, category: space_theme)
ProductCategory.create(product: gagarin_notebook, category: space_theme)
ProductCategory.create(product: gagarin_tote, category: space_theme)
ProductCategory.create(product: gagarin_tshirt, category: space_theme)
ProductCategory.create(product: ipad_case_cosmonaut, category: space_theme)
ProductCategory.create(product: cosmonaut_matryoshka, category: space_theme)
ProductCategory.create(product: cosmonaut_matryoshka, category: toys_theme)
ProductCategory.create(product: cosmonaut_notebook, category: space_theme)
ProductCategory.create(product: poyekhali_notebook, category: space_theme)
ProductCategory.create(product: poyekhali_travel_mug, category: space_theme)
ProductCategory.create(product: prints_cosmonauts, category: space_theme)
ProductCategory.create(product: cosmos_fridge_magnets, category: space_theme)
ProductCategory.create(product: soviet_cosmonaut_matryoshka, category: space_theme)
ProductCategory.create(product: soviet_cosmonaut_matryoshka, category: toys_theme)
ProductCategory.create(product: soviet_rocket_print, category: space_theme)
ProductCategory.create(product: soviet_space_station_print, category: space_theme)
ProductCategory.create(product: spacewalk_print, category: space_theme)
ProductCategory.create(product: spacewalk_pendant, category: space_theme)
ProductCategory.create(product: sputnik_pendant_necklace, category: space_theme)
ProductCategory.create(product: sputnik_print, category: space_theme)
ProductCategory.create(product: tereshkova_tote, category: space_theme)
ProductCategory.create(product: tshirt_vostok, category: space_theme)
ProductCategory.create(product: women_cosmonauts_tote, category: space_theme)
ProductCategory.create(product: women_in_science_print, category: space_theme)
ProductCategory.create(product: binoculars, category: ballet_theme)
ProductCategory.create(product: binoculars, category: theatre_theme)
ProductCategory.create(product: diaghilev, category: ballet_theme)
ProductCategory.create(product: blue_nutcracker_pendant, category: ballet_theme)
ProductCategory.create(product: green_nutcracker_pendant, category: ballet_theme)
ProductCategory.create(product: dark_green_nutcracker_pendant, category: ballet_theme)
ProductCategory.create(product: nutcracker_postcard, category: ballet_theme)
ProductCategory.create(product: nutcracker_tote_bag, category: ballet_theme)
ProductCategory.create(product: white_swan_postcard, category: ballet_theme)
ProductCategory.create(product: black_swan_postcard, category: ballet_theme)
ProductCategory.create(product: indoors_swan_lake, category: ballet_theme)
ProductCategory.create(product: outdoors_swan_lake, category: ballet_theme)
ProductCategory.create(product: snow_queen_tote, category: ballet_theme)
ProductCategory.create(product: december, category: winter_theme)
ProductCategory.create(product: december, category: art_theme)
ProductCategory.create(product: sleeping_forest, category: winter_theme)
ProductCategory.create(product: sleeping_forest, category: art_theme)
ProductCategory.create(product: sleeping_forest, category: forest_theme)
ProductCategory.create(product: old_house, category: winter_theme)
ProductCategory.create(product: old_house, category: art_theme)
ProductCategory.create(product: pigeons, category: winter_theme)
ProductCategory.create(product: pigeons, category: art_theme)
ProductCategory.create(product: shishkov_house, category: winter_theme)
ProductCategory.create(product: shishkov_house, category: art_theme)
ProductCategory.create(product: sunday_melancholy, category: winter_theme)
ProductCategory.create(product: sunday_melancholy, category: art_theme)
ProductCategory.create(product: snowman_matryoshka, category: winter_theme)
ProductCategory.create(product: snowman_matryoshka, category: toys_theme)
ProductCategory.create(product: santa_matryoshka, category: winter_theme)
ProductCategory.create(product: santa_matryoshka, category: toys_theme)
ProductCategory.create(product: winter_coasters, category: winter_theme)
ProductCategory.create(product: khokhloma_cups, category: food_and_drink_theme)
ProductCategory.create(product: khokhloma_spoons, category: food_and_drink_theme)
ProductCategory.create(product: khokhloma_teapot, category: food_and_drink_theme)
ProductCategory.create(product: khokhloma_tray, category: food_and_drink_theme)
ProductCategory.create(product: alenka, category: food_and_drink_theme)
ProductCategory.create(product: apple_chopping_board, category: food_and_drink_theme)
ProductCategory.create(product: babaeyevksy, category: food_and_drink_theme)
ProductCategory.create(product: creme_brulee_truffles, category: food_and_drink_theme)
ProductCategory.create(product: bears_to_the_forest, category: food_and_drink_theme)
ProductCategory.create(product: bears_to_the_forest, category: forest_theme)
ProductCategory.create(product: chocolate_truffles, category: food_and_drink_theme)
ProductCategory.create(product: fridge_magnet_samovar, category: food_and_drink_theme)
ProductCategory.create(product: pear_chopping_board, category: food_and_drink_theme)
ProductCategory.create(product: red_october_chocs_1, category: food_and_drink_theme)
ProductCategory.create(product: red_october_chocs_2, category: food_and_drink_theme)
ProductCategory.create(product: samovar, category: food_and_drink_theme)
ProductCategory.create(product: small_alenka_wafer_chocs, category: food_and_drink_theme)
ProductCategory.create(product: cheburashka_figurine, category: toys_theme)
ProductCategory.create(product: balalaika_figurine, category: toys_theme)
ProductCategory.create(product: balalaika_figurine, category: music_theme)
ProductCategory.create(product: beer_figurine, category: toys_theme)
ProductCategory.create(product: dino_matryoshka, category: toys_theme)
ProductCategory.create(product: fairytale_matroshka, category: toys_theme)
ProductCategory.create(product: girl_cat_figurine, category: toys_theme)
ProductCategory.create(product: masha_bear_figurine, category: toys_theme)
ProductCategory.create(product: rooster_matryoshka, category: toys_theme)
ProductCategory.create(product: milkmaid_matryoshka, category: toys_theme)
ProductCategory.create(product: penguin_matryoshka, category: toys_theme)
ProductCategory.create(product: banya_figurine, category: toys_theme)
ProductCategory.create(product: musician_figurine, category: toys_theme)
ProductCategory.create(product: musician_figurine, category: music_theme)
ProductCategory.create(product: world_cup_map, category: sports_theme)
ProductCategory.create(product: world_cup_poster, category: sports_theme)
ProductCategory.create(product: figure_skater_poster, category: sports_theme)
ProductCategory.create(product: ice_hockey_mug, category: sports_theme)
ProductCategory.create(product: ice_hockey_notebook, category: sports_theme)
ProductCategory.create(product: hockey_stick, category: sports_theme)
ProductCategory.create(product: hockey_tote, category: sports_theme)
ProductCategory.create(product: basketball_print, category: sports_theme)
ProductCategory.create(product: gymnastics_print, category: sports_theme)
ProductCategory.create(product: swimmer_pendant, category: sports_theme)
ProductCategory.create(product: figure_skater_mug, category: sports_theme)
ProductCategory.create(product: ice_hockey_poster, category: sports_theme)
ProductCategory.create(product: birch_tree_coaster, category: forest_theme)
ProductCategory.create(product: birch_trees_painting, category: forest_theme)
ProductCategory.create(product: birch_trees_painting, category: art_theme)
ProductCategory.create(product: dancing_cats_tablemat, category: forest_theme)
ProductCategory.create(product: pine_branches, category: forest_theme)
ProductCategory.create(product: rainbow_tablemat, category: forest_theme)
ProductCategory.create(product: hedgehog_tablemat, category: forest_theme)
ProductCategory.create(product: hedgehog_notebook, category: forest_theme)
ProductCategory.create(product: forest_matryoshka, category: forest_theme)
ProductCategory.create(product: forest_matryoshka, category: toys_theme)
ProductCategory.create(product: old_birch, category: forest_theme)
ProductCategory.create(product: old_birch, category: art_theme)
ProductCategory.create(product: owl_print, category: forest_theme)
ProductCategory.create(product: owl_chopping_board, category: forest_theme)
ProductCategory.create(product: owl_notebook, category: forest_theme)
ProductCategory.create(product: fridge_magnet, category: forest_theme)
ProductCategory.create(product: rabbit_tablemat, category: forest_theme)
ProductCategory.create(product: rainbow_chopping_board, category: forest_theme)
ProductCategory.create(product: rainbow_notebook, category: forest_theme)
ProductCategory.create(product: four_tablemats, category: forest_theme)


puts "------------------------------------------------SEEDED------------------------------------------------------"
